### ISSUE TITLE
How to make session open and send deliver_sm command for MO from SMSC

### ISSUE THREAD

**Issue by senthilkumargsm** [theodorosidmar/smpp-server-simulator#2]
Could you help on, how to open a session and trigger a deliver_sm command from SMPP server, when it received MO from the mobile?

**Comment by ataquino** [comment]
Hello. Could you please clarify your question? As I understand it, you want to trigger the deliver_sm event on MO messages, is that it? If that is the case, this package is not for you. This is simply a simulator of SMPP servers, for testing purposes. 

If you want to simulate a deliver_sm command for MO messages, you can do so by setting a timeout or interval in `src/server/index.js`, using the `session` object:

```js
module.exports = smpp.createServer((session) => {
  session.on('bind_transceiver', bindTransceiver.bind(this, session))
  session.on('unbind', unbind.bind(this, session))
  session.on('enquire_link', enquireLink.bind(this, session))
  session.on('submit_sm', submitSm.bind(this, session))
  session.on('query_sm', querySm.bind(this, session))
  session.on('error', error.bind(this, error))
  setInterval(() => {
    session.deliver_sm({
      // required properties
    });
  }, 5000);
})
```

If you actually want to connect to an SMSC, you need a client package, such as [this one](https://www.npmjs.com/package/smpp).

I hope that answers your question. If not, feel free to elaborate.

**Comment by senthilkumargsm** [comment]
Basically, my scenario is this,

My Client (ESME) is generating the SMS delivery, but my client works only with SMPP end point, also we don’t want to use the external aggregators and instead we want our own in-house SMS Rest based API as SMS service.

Now we need to build a bridge for this case, so we thought of using smpp-server-simulator opensource. What we did is we have installed this open source in one of the server, so that it will act as SMPP server or endpoint and able to get the SMPP commands from the client. Inside this server we are implementing the SMPP command like as follows in **submit-sm.js:**

--------------------------------------------------
const { log } = require('../../utils/logger')
const request = require("request");

module.exports = (session, pdu) => {
    log("this is submitsm")
    log(pdu)
    const msg = pdu["short_message"]["message"];
    const endpoint = "https://smsdeliveryconnector/sendsms";
    const messageId = Math.floor(new Date()).toString().substring(4)
      request.post(endpoint,
         { json: {
           "address": pdu["destination_addr"],
             "message": msg,
             "messageId": messageId
         }},
         function (err, res, body) {
           console.log(body);
         });


    log(pdu.response({ message_id: messageId }))

    //Send submit_sm_resp
    session.send(pdu.response({ message_id: messageId }))

   //call session.deliver_sm for delivery receipt  
   //instead of calling a delivery immediately here, my sms api will return the delivery receipt in bulk with delay, so i need to invoke this command in asynchronous manner.
}
------------------------------------------

**Comment by senthilkumargsm** [comment]
Also for MO cases, where to write deliver_sm trigger?

**Comment by ataquino** [comment]
As I stated previously, this is not an SMPP server, it's simply to be used as a simulator.

What you need is to look into [this SMPP package](https://www.npmjs.com/package/smpp), which we also use, and build a server around it. 

In your scenario, you should Store the client session somewhere, so you can interact with it when your api returns the delivery receipt. When it does, simply call session.deliver_sm with it's required parameters (as stated in the SMPP protocol).

Also, as this project is not intended to be an SMPP server, I'll be closing this.
